In [171]:
import numpy as np

In [172]:
y = np.array([2955.53, 2.28, 334.32, 3670.48, 1709.09, 13.08, 864.44, 560.30, 2202.93])
X = np.zeros((9, 3))
w = np.zeros((10, 3, 1))
x = np.array([35.38, 0.29, 11.74, 39.45, 26.85, 3.98, 19.05, 15.32, 30.51])

In [173]:
X[:, 0] = x.T ** 2
X[:, 1] = x.T
X[:, 2] = np.ones((9))

In [174]:
alpha = 0.001
r = np.array([0, 7, 2, 6, 4, 3, 8, 5, 1])

In [175]:
for i in range(1, 10):
    w[i, :, :] = w[i - 1, :, :] - (alpha * (-X[r[i - 1]].T * (y[r[i - 1]] - np.dot(X[r[i - 1]], w[i - 1, :, :])))).reshape((3, 1))

In [176]:
print(w)

[[[ 0.00000000e+00]
  [ 0.00000000e+00]
  [ 0.00000000e+00]]

 [[ 3.69956813e+03]
  [ 1.04566651e+02]
  [ 2.95553000e+00]]

 [[-2.00337117e+05]
  [-1.32137549e+04]
  [-8.66386605e+02]]

 [[ 3.62690299e+06]
  [ 3.12786255e+05]
  [ 2.69019277e+04]]

 [[-4.76201614e+08]
  [-2.48750624e+07]
  [-1.29529485e+06]]

 [[ 2.47502142e+11]
  [ 9.21081745e+09]
  [ 3.42678355e+08]]

 [[-5.99787903e+14]
  [-1.52008121e+13]
  [-3.85209234e+11]]

 [[ 5.19548815e+17]
  [ 1.70332621e+16]
  [ 5.58397580e+14]]

 [[ 3.88101820e+17]
  [-1.59936210e+16]
  [-7.73981425e+15]]

 [[ 3.88100116e+17]
  [-1.59994968e+16]
  [-7.76007565e+15]]]
